project:
  type: website
  render:
    - "*.qmd"
    - "!notebooks/"
    - "!scripts/"
  post-render: mv *.ipynb notebooks/

website:
  title: "BINF200 Biological Sequences and Structures"
  navbar:
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Assignments"
        contents:
          - assignment_PacBio_VSG.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



